### ISSUE TITLE
out of the box config isn't working

### ISSUE THREAD

**Issue by sreilly** [JavaEden/OrchidStarter#1]
With a fresh clone of OrchidStarter on macOS 10.13.3 and using the latest master (with Updates to Orchid 0.8.1), running ./gradlew orchidServe (or orchidBuild) fails with the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'OrchidStarter'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find gradle.plugin.buildSrc:orchidPlugin:0.8.1.
     Searched in the following locations:
         https://jcenter.bintray.com/gradle/plugin/buildSrc/orchidPlugin/0.8.1/orchidPlugin-0.8.1.pom
         https://jcenter.bintray.com/gradle/plugin/buildSrc/orchidPlugin/0.8.1/orchidPlugin-0.8.1.jar
         https://plugins.gradle.org/m2/gradle/plugin/buildSrc/orchidPlugin/0.8.1/orchidPlugin-0.8.1.pom
         https://plugins.gradle.org/m2/gradle/plugin/buildSrc/orchidPlugin/0.8.1/orchidPlugin-0.8.1.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

Before this commit both orchidServe and orchidBuild worked fine.  I'm new to Gradle so hopefully the above message makes sense to you and is fixable.  Orchid seems like just what I've been looking for, so hopefully this is an easy fix!

**Comment by cjbrooks12** [comment]
Sorry about that! I moved the Gradle plugins to a continuous delivery with 0.8.0, but it ended up not working like I expected. The plugin package is now changed and is fixed in 0.8.2, and I've updated this project with the new version. Pull down from master and try again!
