### ISSUE TITLE
Converting java code to Kotlin?

### ISSUE THREAD

**Issue by jmfayard** [JavaEden/OrchidStarter#6]
Hello, 
I plan to convert for me the sample converter from `OrchidStarter` from Java to Kotlin
https://github.com/JavaEden/OrchidStarter/tree/master/src/orchid/java/com/eden/orchid/starter

Would you be iterested by a pull-request for this?
We can point it to git history for those interested in having it in Java

**Comment by cjbrooks12** [comment]
Absolutely, I would love this! The more Kotlin, the better!

**Comment by jmfayard** [comment]
Done! the Java code is available at:
https://github.com/JavaEden/OrchidStarter/tree/ad69f3521ec49745ae1d1908c8441e5c9305af97/src/orchid/java/com/eden/orchid/starter
